application: pig-latin-translator
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /pig\.ico
  static_files: pig.ico
  upload: pig\.ico

- url: /stylesheets
  static_dir: stylesheets

- url: /images
  static_dir: images

- url: .*
  script: main.app

libraries:
- name: jinja2
  version: latest
- name: webapp2
  version: "2.5.2"
